# This is a basic workflow to help you get started with Actions

name: Test Matplotlib Release

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Check for new matplotlib releases and run tests if a new release is available
  test-on-mpl-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2
      
      # Get mpl version reference file from last run
      # The test script uses this to compare if a new version of mpl has been released since
      # the last run
      - name: Download version file
        uses: actions/download-artifact@v2
        with:
          name: last-mpl-version

      # Runs the test script; the script will do all the version checks and
      # environment updates, if required
      - name: Run test script
        run: ./timple/tests/test_new_mpl_releases.sh
        shell: bash

      # Upload the potentially updated mpl version reference file
      - name: Upload version file
        uses: actions/upload-artifact@v1
        with:
          name: last-mpl-version
          path: last_mpl_version.txt
